services:
  web:
    image: nginx
    volumes:
      - ./docker/templates:/etc/nginx/templates
      - ./dist-dev:/usr/share/nginx/html
      - ./certs:/etc/ssl
    ports:
      - 80:80
      - 443:443
