[package]
name = "test_utils"
version = "0.1.0"
edition = "2021"

[dependencies]
ic-certification = { path = "../../../rs/certification" }
ic-certification-test-utils = { path = "../../../rs/certification/test-utils" }
ic-crypto = { path = "../../../rs/crypto" }
ic-crypto-tree-hash = { path = "../../../rs/crypto/tree_hash" }
ic-crypto-utils-threshold-sig = { path = "../../../rs/crypto/utils/threshold_sig" }
ic-crypto-utils-threshold-sig-der = { path = "../../../rs/crypto/utils/threshold_sig_der" }
ic-types = { path = "../../../rs/types/types" }
ic-base-types = { path = "../../../rs/types/base_types" }

serde = { version = "1.0", features = ['derive'] }
serde_cbor = "0.11"
serde_json = "1.0.86"
hex = "0.4"
ic-certified-map = "0.3.1"
rand = "0.8"
base64 = "0.13"
sha256 = "1.0"
